config/routes.rb
Bizkit10::Application.routes.draw do
  resources :rounds

  resources :simulations

  resources :facilitators

  resources :institutes

  resources :student_group_users

  resources :student_groups

  resources :facilitator_group_users

  resources :facilitator_groups
  resources :imports

  devise_for :users

  get "round_decision/new"

  resources :start_up_decisions
  resources :round_decision

match 'participation_management'=>'welcome#participation_management'
  match 'set_participation'=>'welcome#set_participation'
  match 'remove_student/:student_group_user_id', :to=>'welcome#remove_student'
  match 'set_simulation'=>'welcome#set_simulation'
  match 'remove_student_from_list/:user_id'=>'welcome#remove_student_from_list'

   root :to => 'welcome#index'

end

app/models/active_round.rb
class ActiveRound < ActiveRecord::Base
end

app/models/advertising.rb
class Advertising < ActiveRecord::Base
end

app/models/channel_incentive.rb
class ChannelIncentive < ActiveRecord::Base
end

app/models/facilitator.rb
class Facilitator < ActiveRecord::Base
  has_many :facilitator_institutes
  has_many :institutes,:through => :facilitator_institutes
end

app/models/import.rb
class Import < ActiveRecord::Base
  has_attached_file :excel
end

app/models/institute.rb
class Institute < ActiveRecord::Base
  has_many :facilitator_institutes
  has_many :facilitators,:through => :facilitator_institutes
  has_many :student_groups,:dependent => :destroy
end

app/models/market.rb
class Market < ActiveRecord::Base
end

app/models/packaging.rb
class Packaging < ActiveRecord::Base
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :simulation

  def self.create_rounds(simulation_id)
    @simulation=Simulation.find(simulation_id)
    @simulation.max_rounds.times do |i|
      @round=Round.new
      @round.number=i+1
      @round.simulation_id=@simulation.id
      @round.save!
    end

  end
end

app/models/round_factories.rb
class RoundFactories < ActiveRecord::Base
end

app/models/round_market.rb
class RoundMarket < ActiveRecord::Base
end

app/models/round_price.rb
class RoundPrice < ActiveRecord::Base
end

app/models/simulation.rb
class Simulation < ActiveRecord::Base

  has_many :rounds, :dependent => :destroy

  after_create :create_rounds
  def create_rounds

    Round.create_rounds(self.id)
  end
end

app/models/size.rb
class Size < ActiveRecord::Base
end

app/models/student_group.rb
class StudentGroup < ActiveRecord::Base
  belongs_to :institute
end

app/models/taste.rb
class Taste < ActiveRecord::Base
end

app/models/topping.rb
class Topping < ActiveRecord::Base
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :facilitator_group_users
  has_many :facilitator_groups ,:through => :facilitator_group_users

 # after_save :create_fg

  def create_fg
    if self.facilitator?
      FacilitatorGroup.create_my_group(self.id)
    end

  end

  def full_name
    [first_name , last_name].join(" ")
  end

  require "spreadsheet"

  def self.mass_create_users(import_id)
    @import=Import.find(import_id)
    @path=@import.excel.path
    book = Spreadsheet.open @path
    sheet1 = book.worksheet 0

    sheet1.each 1 do |row|

      if User.find_by_email(row[4].to_s).nil?

        @user=User.new
        @user.username=row[0]
        @user.first_name=row[1]
        @user.last_name=row[2]
        @user.password=row[3]
        @user.password_confirmation=row[3]
        @user.email=row[4].to_s
        @user.superadmin=row[5]
        @user.admin=row[6]
        @user.facilitator=row[7]
        @user.student=row[8]
        @user.institute_id=@import.institute_id
        @user.save!


      else
        @user= User.find_by_email(row[4].to_s)

      end


    end
  end
end

app/controllers/student_groups_controller.rb
class StudentGroupsController < ApplicationController
  # GET /student_groups
  # GET /student_groups.json
  def index
    @facilitator=Facilitator.find_by_user_id(current_user.id)
    @institutes=@facilitator.institutes
    @student_groups=@institutes.collect{|inst|inst.student_groups}

    @student_groups = StudentGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @student_groups }
    end
  end

  # GET /student_groups/1
  # GET /student_groups/1.json
  def show
    @student_group = StudentGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student_group }
    end
  end

  # GET /student_groups/new
  # GET /student_groups/new.json
  def new
    @student_group = StudentGroup.new
    @facilitator=Facilitator.find_by_user_id(current_user.id)
    @institutes=@facilitator.institutes.collect{|institute|[institute.name,institute.id]}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student_group }
    end
  end

  # GET /student_groups/1/edit
  def edit
    @student_group = StudentGroup.find(params[:id])
  end

  # POST /student_groups
  # POST /student_groups.json
  def create
    @student_group = StudentGroup.new(params[:student_group])

    respond_to do |format|
      if @student_group.save
        format.html { redirect_to @student_group, notice: 'Student group was successfully created.' }
        format.json { render json: @student_group, status: :created, location: @student_group }
      else
        format.html { render action: "new" }
        format.json { render json: @student_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /student_groups/1
  # PUT /student_groups/1.json
  def update
    @student_group = StudentGroup.find(params[:id])

    respond_to do |format|
      if @student_group.update_attributes(params[:student_group])
        format.html { redirect_to @student_group, notice: 'Student group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @student_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_groups/1
  # DELETE /student_groups/1.json
  def destroy
    @student_group = StudentGroup.find(params[:id])
    @student_group.destroy

    respond_to do |format|
      format.html { redirect_to student_groups_url }
      format.json { head :ok }
    end
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/student_groups_helper.rb
module StudentGroupsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/student_groups/_form.html.erb
<%= form_for(@student_group) do |f| %>
  <% if @student_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_group.errors.count, "error") %> prohibited this student_group from being saved:</h2>

      <ul>
      <% @student_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :name %>
    <div class="input">
    <%= f.text_field :name %>
      </div>
  </div>
  <div class="clearfix">
    <%= f.label :institute_id %>
    <div class="input">

    <%= f.select :institute_id ,@institutes%>
      </div>
  </div>
  <div class="row pull-right">
    <%= f.submit "Submit",:class=>"primary btn"%>
  </div>
<% end %>

app/views/student_groups/edit.html.erb
<h1>Editing student_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_group %> |
<%= link_to 'Back', student_groups_path %>

app/views/student_groups/index.html.erb
<h1>Listing student_groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Institute</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @student_groups.each do |student_group| %>
  <tr>
    <td><%= student_group.name %></td>
    <td><%= student_group.institute_id %></td>
    <td><%= link_to 'Show', student_group %></td>
    <td><%= link_to 'Edit', edit_student_group_path(student_group) %></td>
    <td><%= link_to 'Destroy', student_group, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student group', new_student_group_path %>

app/views/student_groups/new.html.erb
<%= content_for :page_header do %>
<h1>New student_group</h1>
    <% end %>

<%= render 'form' %>

<%= link_to 'Back', student_groups_path %>

app/views/student_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student_group.name %>
</p>

<p>
  <b>Institute:</b>
  <%= @student_group.institute_id %>
</p>


<%= link_to 'Edit', edit_student_group_path(@student_group) %> |
<%= link_to 'Back', student_groups_path %>