config/routes.rb
Bizkit10::Application.routes.draw do
  resources :rounds

  resources :simulations

  resources :facilitators

  resources :institutes

  resources :student_group_users

  resources :student_groups

  resources :facilitator_group_users

  resources :facilitator_groups
  resources :imports

  devise_for :users

  get "round_decision/new"

  resources :start_up_decisions
  resources :round_decision

match 'participation_management'=>'welcome#participation_management'
  match 'set_participation'=>'welcome#set_participation'
  match 'remove_student/:student_group_user_id', :to=>'welcome#remove_student'
  match 'set_simulation'=>'welcome#set_simulation'
  match 'remove_student_from_list/:user_id'=>'welcome#remove_student_from_list'

   root :to => 'welcome#index'

end

app/models/active_round.rb
class ActiveRound < ActiveRecord::Base
end

app/models/advertising.rb
class Advertising < ActiveRecord::Base
end

app/models/facilitator.rb
class Facilitator < ActiveRecord::Base
  has_many :facilitator_institutes
  has_many :institutes,:through => :facilitator_institutes
end

app/models/import.rb
class Import < ActiveRecord::Base
  has_attached_file :excel
end

app/models/institute.rb
class Institute < ActiveRecord::Base
  has_many :facilitator_institutes
  has_many :facilitators,:through => :facilitator_institutes
  has_many :student_groups,:dependent => :destroy
end

app/models/market.rb
class Market < ActiveRecord::Base
end

app/models/packaging.rb
class Packaging < ActiveRecord::Base
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :simulation

  def self.create_rounds(simulation_id)
    @simulation=Simulation.find(simulation_id)
    @simulation.max_rounds.times do |i|
      @round=Round.new
      @round.number=i+1
      @round.simulation_id=@simulation.id
      @round.save!
    end

  end
end

app/models/round_factories.rb
class RoundFactories < ActiveRecord::Base
end

app/models/round_market.rb
class RoundMarket < ActiveRecord::Base
end

app/models/round_price.rb
class RoundPrice < ActiveRecord::Base
end

app/models/simulation.rb
class Simulation < ActiveRecord::Base

  has_many :rounds, :dependent => :destroy

  after_create :create_rounds
  def create_rounds

    Round.create_rounds(self.id)
  end
end

app/models/size.rb
class Size < ActiveRecord::Base
end

app/models/start_up_decision.rb
class StartUpDecision < ActiveRecord::Base
end

app/models/student_group.rb
class StudentGroup < ActiveRecord::Base
  belongs_to :institute
end

app/models/taste.rb
class Taste < ActiveRecord::Base
end

app/models/topping.rb
class Topping < ActiveRecord::Base
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :facilitator_group_users
  has_many :facilitator_groups ,:through => :facilitator_group_users

 # after_save :create_fg

  def create_fg
    if self.facilitator?
      FacilitatorGroup.create_my_group(self.id)
    end

  end

  def full_name
    [first_name , last_name].join(" ")
  end

  require "spreadsheet"

  def self.mass_create_users(import_id)
    @import=Import.find(import_id)
    @path=@import.excel.path
    book = Spreadsheet.open @path
    sheet1 = book.worksheet 0

    sheet1.each 1 do |row|

      if User.find_by_email(row[4].to_s).nil?

        @user=User.new
        @user.username=row[0]
        @user.first_name=row[1]
        @user.last_name=row[2]
        @user.password=row[3]
        @user.password_confirmation=row[3]
        @user.email=row[4].to_s
        @user.superadmin=row[5]
        @user.admin=row[6]
        @user.facilitator=row[7]
        @user.student=row[8]
        @user.institute_id=@import.institute_id
        @user.save!


      else
        @user= User.find_by_email(row[4].to_s)

      end


    end
  end
end

app/controllers/start_up_decisions_controller.rb
class StartUpDecisionsController < ApplicationController
  # GET /start_up_decisions
  # GET /start_up_decisions.json

  before_filter :initialize_variables

  def initialize_variables
    @player_id=1
    @simulation_id=1

  end

  def index
    @start_up_decisions = StartUpDecision.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @start_up_decisions }
    end
  end

  # GET /start_up_decisions/1
  # GET /start_up_decisions/1.json
  def show
    @start_up_decision = StartUpDecision.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @start_up_decision }
    end
  end

  # GET /start_up_decisions/new
  # GET /start_up_decisions/new.json
  def new
    if !StartUpDecision.find_by_player_id(@player_id).nil?
      redirect_to StartUpDecision.find_by_player_id(@player_id)
    else
      @start_up_decision = StartUpDecision.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @start_up_decision }
      end
    end
  end

  # GET /start_up_decisions/1/edit
  def edit
    @start_up_decision = StartUpDecision.find(params[:id])
  end

  # POST /start_up_decisions
  # POST /start_up_decisions.json
  def create
    @start_up_decision = StartUpDecision.new(params[:start_up_decision])
    @price=0
    @price=@price+Taste.find(@start_up_decision.taste_id).price
    @price=@price+Type.find(@start_up_decision.type_id).price
    @price=@price+Packaging.find(@start_up_decision.packaging_id).price
    @price=@price+Topping.find(@start_up_decision.topping_id).price

    @start_up_decision.cost_price=@price


    respond_to do |format|
      if @start_up_decision.save
        format.html { redirect_to @start_up_decision, notice: 'Start up decision was successfully created.' }
        format.json { render json: @start_up_decision, status: :created, location: @start_up_decision }
      else
        format.html { render action: "new" }
        format.json { render json: @start_up_decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /start_up_decisions/1
  # PUT /start_up_decisions/1.json
  def update
    @start_up_decision = StartUpDecision.find(params[:id])

    respond_to do |format|
      if @start_up_decision.update_attributes(params[:start_up_decision])
        format.html { redirect_to @start_up_decision, notice: 'Start up decision was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @start_up_decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /start_up_decisions/1
  # DELETE /start_up_decisions/1.json
  def destroy
    @start_up_decision = StartUpDecision.find(params[:id])
    @start_up_decision.destroy

    respond_to do |format|
      format.html { redirect_to start_up_decisions_url }
      format.json { head :ok }
    end
  end

  def get_price

  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/start_up_decisions_helper.rb
module StartUpDecisionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/start_up_decisions/_form.html.erb
<%= content_for :page_header do %>

    <h1>Start Up Decisions</h1>
    <h5>Cost Price:</h5><p class="cost_price">0</p>

<% end %>


<div id="wrapper">
  <div id="steps">
    <%= form_for(@start_up_decision) do |f| %>
        <%= f.hidden_field :player_id, :value=>@player_id %>

        <%= f.hidden_field :simulation_id, :value=>@simulation_id %>

        <% if @start_up_decision.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@start_up_decision.errors.count, "error") %> prohibited this start_up_decision from
                being saved:</h2>

              <ul>
                <% @start_up_decision.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <fieldset class="step">
          <legend>Taste</legend>

          <div class="clearfix">

            <%= f.label :taste_id %>
            <div class="input">
              <%= f.select :taste_id, Taste.all.collect { |taste| [taste.name, taste.id] } %>
            </div>
          </div>


        </fieldset>

        <fieldset class="step">
          <legend>Type</legend>

          <div class="clearfix">

            <%= f.label :type_id %>
            <div class="input">
              <%= f.select :type_id, Type.all.collect { |type| [type.name, type.id] } %>
            </div>
          </div>
        </fieldset>

        <fieldset class="step">
          <legend>Topping</legend>
          <div class="clearfix">

            <%= f.label :topping_id %>
            <div class="input">
              <%= f.select :topping_id, Topping.all.collect { |topping| [topping.name, topping.id] } %>
            </div>
          </div>
        </fieldset>


        <fieldset class="step">
          <legend>Packaging</legend>
          <div class="clearfix">

            <%= f.label :packaging_id %>
            <div class="input">
              <%= f.select :packaging_id, Packaging.all.collect { |packaging| [packaging.name, packaging.id] }, :class=>"medium" %>

            </div>
          </div>
        </fieldset>

        <fieldset class="step">
          <legend>Brand Name</legend>
          <div class="clearfix">

            <%= f.label :brand_name %>
            <div class="input">
              <%= f.text_field :brand_name, %>

            </div>
          </div>
        </fieldset>


        <fieldset class="step">

          <legend>Submit</legend>
          <div class="actions">
            <%= f.submit "Confirm", :class=>"btn " %>
          </div>
        </fieldset>
    <% end %>


  </div>

  <div id="navigation" style="display:none;">
    <ul>
      <li class="selected">
        <a href="#">Taste</a>
      </li>
      <li>
        <a href="#">Type</a>
      </li>
      <li>
        <a href="#">Topping</a>
      </li>
      <li>
        <a href="#">Packaging</a>
      </li>
      <li>
        <a href="#">Brand </a>
      </li>

      <li>
        <a href="#">Submit</a>
      </li>
    </ul>
  </div>

</div>

app/views/start_up_decisions/edit.html.erb
<%= content_for :page_header do %>

<h1>Start Up Decisions</h1>
    <% end %>

<%= render 'form' %>

<%= link_to 'Show', @start_up_decision %> |
<%= link_to 'Back', start_up_decisions_path %>

app/views/start_up_decisions/index.html.erb
<h1>Listing start_up_decisions</h1>

<table>
  <tr>
    <th>Player</th>
    <th>Simulation</th>
    <th>Taste</th>
    <th>Type</th>
    <th>Topping</th>
    <th>Packaging</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @start_up_decisions.each do |start_up_decision| %>
  <tr>
    <td><%= start_up_decision.player_id %></td>
    <td><%= start_up_decision.simulation_id %></td>
    <td><%= start_up_decision.taste_id %></td>
    <td><%= start_up_decision.type_id %></td>
    <td><%= start_up_decision.topping_id %></td>
    <td><%= start_up_decision.packaging_id %></td>
    <td><%= link_to 'Show', start_up_decision %></td>
    <td><%= link_to 'Edit', edit_start_up_decision_path(start_up_decision) %></td>
    <td><%= link_to 'Destroy', start_up_decision, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Start up decision', new_start_up_decision_path %>

app/views/start_up_decisions/new.html.erb
<%= content_for :page_header do %>


    <% end %>

<%= render 'form' %>

<%= link_to 'Back', start_up_decisions_path %>

app/views/start_up_decisions/show.html.erb
<%= content_for :page_header do %>
    <h2>Showing start up decisions for player <%= @start_up_decision.player_id %></h2>
<% end %>

<p id="notice"><%= notice %></p>


<p>
  <b>Taste:</b>
  <%= Taste.find(@start_up_decision.taste_id).name %>
</p>

<p>
  <b>Type:</b>
  <%= Type.find(@start_up_decision.type_id).name %>
</p>

<p>
  <b>Topping:</b>
  <%= Topping.find(@start_up_decision.topping_id).name %>
</p>

<p>
  <b>Packaging:</b>
  <%= Packaging.find(@start_up_decision.packaging_id).name %>
</p>
<p>
  <b>Name:</b>
  <%= @start_up_decision.brand_name %>
</p>



<%= link_to 'Edit', edit_start_up_decision_path(@start_up_decision) %> |
<%= link_to 'Back', start_up_decisions_path %>

<%= content_for :secondary_area do%>
    <%= link_to "Proceed for Round Data >>",new_round_decision_path,:class => "primary btn" %>

<% end %>