config/routes.rb
Bizkit10::Application.routes.draw do
  resources :rounds

  resources :simulations

  resources :facilitators

  resources :institutes

  resources :student_group_users

  resources :student_groups

  resources :facilitator_group_users

  resources :facilitator_groups
  resources :imports

  devise_for :users

  get "round_decision/new"

  resources :start_up_decisions
  resources :round_decision

match 'participation_management'=>'welcome#participation_management'
  match 'set_participation'=>'welcome#set_participation'
  match 'remove_student/:student_group_user_id', :to=>'welcome#remove_student'
  match 'set_simulation'=>'welcome#set_simulation'
  match 'remove_student_from_list/:user_id'=>'welcome#remove_student_from_list'

   root :to => 'welcome#index'

end

app/models/active_round.rb
class ActiveRound < ActiveRecord::Base
end

app/models/advertising.rb
class Advertising < ActiveRecord::Base
end

app/models/channel_incentive.rb
class ChannelIncentive < ActiveRecord::Base
end

app/models/facilitator.rb
class Facilitator < ActiveRecord::Base
  has_many :facilitator_institutes
  has_many :institutes,:through => :facilitator_institutes
end

app/models/import.rb
class Import < ActiveRecord::Base
  has_attached_file :excel
end

app/models/institute.rb
class Institute < ActiveRecord::Base
  has_many :facilitator_institutes
  has_many :facilitators,:through => :facilitator_institutes
  has_many :student_groups,:dependent => :destroy
end

app/models/market.rb
class Market < ActiveRecord::Base
end

app/models/packaging.rb
class Packaging < ActiveRecord::Base
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :simulation

  def self.create_rounds(simulation_id)
    @simulation=Simulation.find(simulation_id)
    @simulation.max_rounds.times do |i|
      @round=Round.new
      @round.number=i+1
      @round.simulation_id=@simulation.id
      @round.save!
    end

  end
end

app/models/round_factories.rb
class RoundFactories < ActiveRecord::Base
end

app/models/round_market.rb
class RoundMarket < ActiveRecord::Base
end

app/models/round_price.rb
class RoundPrice < ActiveRecord::Base
end

app/models/simulation.rb
class Simulation < ActiveRecord::Base

  has_many :rounds, :dependent => :destroy

  after_create :create_rounds
  def create_rounds

    Round.create_rounds(self.id)
  end
end

app/models/size.rb
class Size < ActiveRecord::Base
end

app/models/student_group.rb
class StudentGroup < ActiveRecord::Base
  belongs_to :institute
end

app/models/taste.rb
class Taste < ActiveRecord::Base
end

app/models/topping.rb
class Topping < ActiveRecord::Base
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :facilitator_group_users
  has_many :facilitator_groups ,:through => :facilitator_group_users

 # after_save :create_fg

  def create_fg
    if self.facilitator?
      FacilitatorGroup.create_my_group(self.id)
    end

  end

  def full_name
    [first_name , last_name].join(" ")
  end

  require "spreadsheet"

  def self.mass_create_users(import_id)
    @import=Import.find(import_id)
    @path=@import.excel.path
    book = Spreadsheet.open @path
    sheet1 = book.worksheet 0

    sheet1.each 1 do |row|

      if User.find_by_email(row[4].to_s).nil?

        @user=User.new
        @user.username=row[0]
        @user.first_name=row[1]
        @user.last_name=row[2]
        @user.password=row[3]
        @user.password_confirmation=row[3]
        @user.email=row[4].to_s
        @user.superadmin=row[5]
        @user.admin=row[6]
        @user.facilitator=row[7]
        @user.student=row[8]
        @user.institute_id=@import.institute_id
        @user.save!


      else
        @user= User.find_by_email(row[4].to_s)

      end


    end
  end
end

app/controllers/facilitators_controller.rb
class FacilitatorsController < ApplicationController
  # GET /facilitators
  # GET /facilitators.json
  def index
    @facilitators = Facilitator.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @facilitators }
    end
  end

  # GET /facilitators/1
  # GET /facilitators/1.json
  def show
    @facilitator = Facilitator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @facilitator }
    end
  end

  # GET /facilitators/new
  # GET /facilitators/new.json
  def new
    @facilitator = Facilitator.new
    @users=User.where(['facilitator=?',true]).collect{|user|[user.email,user.id]}
    @institutes=Institute.all.collect{|institute|[institute.name,institute.id]}


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @facilitator }
    end
  end

  # GET /facilitators/1/edit
  def edit
    @facilitator = Facilitator.find(params[:id])
  end

  # POST /facilitators
  # POST /facilitators.json
  def create

    if Facilitator.find_by_user_id(params[:facilitator][:user_id]).nil?
    @facilitator = Facilitator.new(params[:facilitator])
    else
    @facilitator=Facilitator.find_by_user_id(params[:facilitator][:user_id])
    end


    respond_to do |format|
      if @facilitator.save
         FacilitatorInstitute.create_entry(@facilitator.id,params[:institute_id])
        format.html { redirect_to @facilitator, notice: 'Facilitator was successfully created.' }
        format.json { render json: @facilitator, status: :created, location: @facilitator }
      else
        format.html { render action: "new" }
        format.json { render json: @facilitator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /facilitators/1
  # PUT /facilitators/1.json
  def update
    @facilitator = Facilitator.find(params[:id])

    respond_to do |format|
      if @facilitator.update_attributes(params[:facilitator])
        format.html { redirect_to @facilitator, notice: 'Facilitator was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @facilitator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilitators/1
  # DELETE /facilitators/1.json
  def destroy
    @facilitator = Facilitator.find(params[:id])
    @facilitator.destroy

    respond_to do |format|
      format.html { redirect_to facilitators_url }
      format.json { head :ok }
    end
  end
end

app/helpers/facilitators_helper.rb
module FacilitatorsHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/facilitators/_form.html.erb
<%= form_for(@facilitator) do |f| %>
  <% if @facilitator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facilitator.errors.count, "error") %> prohibited this facilitator from being saved:</h2>

      <ul>
      <% @facilitator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :user_id %><br />
    <div class="input">
    <%= f.select :user_id,@users %>
      </div>
  </div>

  <div class="clearfix">
    <%= label_tag :institute_id %><br />
    <div class="input">
    <%= select_tag :institute_id,options_for_select(@institutes) %>
      </div>
  </div>


  <div class="row pull-right">
    <%= f.submit "Submit",:class=>"primary btn" %>
  </div>
<% end %>

app/views/facilitators/edit.html.erb
<h1>Editing facilitator</h1>

<%= render 'form' %>

<%= link_to 'Show', @facilitator %> |
<%= link_to 'Back', facilitators_path %>

app/views/facilitators/index.html.erb
<h1>Listing facilitators</h1>

<table>
  <tr>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @facilitators.each do |facilitator| %>
  <tr>
    <td><%= facilitator.user_id %></td>
    <td><%= link_to 'Show', facilitator %></td>
    <td><%= link_to 'Edit', edit_facilitator_path(facilitator) %></td>
    <td><%= link_to 'Destroy', facilitator, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Facilitator', new_facilitator_path %>

app/views/facilitators/new.html.erb
<%= content_for :page_header do %>


    <h1>New facilitator</h1>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', facilitators_path %>

app/views/facilitators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @facilitator.user_id %>
</p>


<%= link_to 'Edit', edit_facilitator_path(@facilitator) %> |
<%= link_to 'Back', facilitators_path %>