config/routes.rb
Bizkit10::Application.routes.draw do
  resources :rounds

  resources :simulations

  resources :facilitators

  resources :institutes

  resources :student_group_users

  resources :student_groups

  resources :facilitator_group_users

  resources :facilitator_groups
  resources :imports

  devise_for :users

  get "round_decision/new"

  resources :start_up_decisions
  resources :round_decision

match 'participation_management'=>'welcome#participation_management'
  match 'set_participation'=>'welcome#set_participation'
  match 'remove_student/:student_group_user_id', :to=>'welcome#remove_student'
  match 'set_simulation'=>'welcome#set_simulation'
  match 'remove_student_from_list/:user_id'=>'welcome#remove_student_from_list'

   root :to => 'welcome#index'

end

app/models/active_round.rb
class ActiveRound < ActiveRecord::Base
end

app/models/advertising.rb
class Advertising < ActiveRecord::Base
end

app/models/channel_incentive.rb
class ChannelIncentive < ActiveRecord::Base
end

app/models/facilitator.rb
class Facilitator < ActiveRecord::Base
  has_many :facilitator_institutes
  has_many :institutes,:through => :facilitator_institutes
end

app/models/import.rb
class Import < ActiveRecord::Base
  has_attached_file :excel
end

app/models/institute.rb
class Institute < ActiveRecord::Base
  has_many :facilitator_institutes
  has_many :facilitators,:through => :facilitator_institutes
  has_many :student_groups,:dependent => :destroy
end

app/models/market.rb
class Market < ActiveRecord::Base
end

app/models/packaging.rb
class Packaging < ActiveRecord::Base
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :simulation

  def self.create_rounds(simulation_id)
    @simulation=Simulation.find(simulation_id)
    @simulation.max_rounds.times do |i|
      @round=Round.new
      @round.number=i+1
      @round.simulation_id=@simulation.id
      @round.save!
    end

  end
end

app/models/round_factories.rb
class RoundFactories < ActiveRecord::Base
end

app/models/round_market.rb
class RoundMarket < ActiveRecord::Base
end

app/models/round_price.rb
class RoundPrice < ActiveRecord::Base
end

app/models/simulation.rb
class Simulation < ActiveRecord::Base

  has_many :rounds, :dependent => :destroy

  after_create :create_rounds
  def create_rounds

    Round.create_rounds(self.id)
  end
end

app/models/size.rb
class Size < ActiveRecord::Base
end

app/models/student_group.rb
class StudentGroup < ActiveRecord::Base
  belongs_to :institute
end

app/models/taste.rb
class Taste < ActiveRecord::Base
end

app/models/topping.rb
class Topping < ActiveRecord::Base
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :facilitator_group_users
  has_many :facilitator_groups ,:through => :facilitator_group_users

 # after_save :create_fg

  def create_fg
    if self.facilitator?
      FacilitatorGroup.create_my_group(self.id)
    end

  end

  def full_name
    [first_name , last_name].join(" ")
  end

  require "spreadsheet"

  def self.mass_create_users(import_id)
    @import=Import.find(import_id)
    @path=@import.excel.path
    book = Spreadsheet.open @path
    sheet1 = book.worksheet 0

    sheet1.each 1 do |row|

      if User.find_by_email(row[4].to_s).nil?

        @user=User.new
        @user.username=row[0]
        @user.first_name=row[1]
        @user.last_name=row[2]
        @user.password=row[3]
        @user.password_confirmation=row[3]
        @user.email=row[4].to_s
        @user.superadmin=row[5]
        @user.admin=row[6]
        @user.facilitator=row[7]
        @user.student=row[8]
        @user.institute_id=@import.institute_id
        @user.save!


      else
        @user= User.find_by_email(row[4].to_s)

      end


    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController



  def index
    if current_user
    @facilitator=Facilitator.find_by_user_id(current_user.id)
      end

  end

end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_index1.html.erb
<script type="text/javascript">
    $(function() {
    })
</script>
<%= content_for :page_header do %>
    <div style="border: none;margin-top: 15px;"><%= image_tag('logo_white.png') %></div>
<% end %>

<div class="row">
  <div class="span10">
    <div class="row">
      <div class="span5" style="font-size:14px;">
        <div class="span4">
          <p>
          <h3>Welcome to Finesse</h3>
          </p>
          A finance strategy simulation conceived and adapted to the Indian markets, conditions and context. The
          simulation helps understand the tradeoffs between quantifiable risks and returns, using a systematic
          methodology
          that adjusts for a variety of finance and business variants. A range of outcomes are arrived that are then
          used
          to make the business decisions.
        </div>
      </div>

      <div class="span5">
        <div style="text-align: left;border-radius: 10px"><%= image_tag("abacus.jpg", :size => "250x295", :style=>"border-radius:10px") %></div>
        <br/>
        <% if !current_user %>
            <div style="text-align: right;color: #556b2f;font-size: 20px;font-weight: bold;margin-right: 30px;">
              <a href="#" data-controls-modal="sign_up_form" data-backdrop="static" class="btn primary ">Sign Up</a>
            </div>
        <% else %>
            <div style="text-align: right;color: #556b2f;font-size: 20px;font-weight: bold;margin-right: 20px;">
              <h2> Welcome</h2>
            </div>
        <% end %>
        <div id="sign_up_form" class="modal hide fade">
          <div class="modal-header">
            <a href="#" class="close"> &times; </a>

            <h3>Sign Up</h3>
          </div>
          <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
              <div class="modal-body">
                <div class="clearfix">
                  <%= f.label :first_name %>
                  <div class="input">  <%= f.text_field :first_name %></div>
                  <br/>
                  <%= f.label :last_name %>
                  <div class="input">  <%= f.text_field :last_name %></div>
                  <br/>
                  <%= f.label :username %>
                  <div class="input">  <%= f.text_field :username %></div>
                  <br/>
                  <%= f.label :email %>
                  <div class="input">  <%= f.email_field :email %></div>
                  <br/>
                  <%= f.label :password %>
                  <div class="input">  <%= f.password_field :password %></div>
                  <br/>
                  <%= f.label :password_confirmation %>
                  <div class="input"><br/> <%= f.password_field :password_confirmation %></div>
                  <br/>
                  <%= f.label :admin %>
                  <div class="input input-prepended"> <%= f.check_box :admin %></div>
                  <br/>
                  <%= f.label :superadmin %>
                  <div class="input input-prepended"> <%= f.check_box :superadmin %></div>
                  <br/>
                  <%= f.label :facilitator %>
                  <div class="input input-prepended"> <%= f.check_box :facilitator %></div>
                  <br/>
                  <%= f.label :student %>
                  <div class="input input-prepended"> <%= f.check_box :student %></div>
                  <br/>

                </div>
              </div>
              <div class="modal-footer">
                <div>
                  <%= f.submit "Sign up", :class=>"btn primary" %>
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="span6">
    <table style="background-color: #ffffff;color: #000000;">
      <tr style="border: none;">
        <td style="border: none;">
          <%= image_tag("cfo.png", :size => "64x64") %>
        </td>
        <td style="border: none;">
          Play the role of a CFO with the power to determine the future of your company. But as they say, with great power comes great responsibility...
        </td>
      </tr>
      <tr>
        <td>
          <%= image_tag("decision.png", :size => "64x64") %>
        </td>
        <td>
          Appreciate the nuances of corporate finance as you approve budgets, decide capital expansion plans and control everything from salary to commissions.
        </td>
      </tr>
      <tr>
        <td>
          <%= image_tag("investment.png", :size => "64x64") %>
        </td>
        <td>
          Understand the fundamentals of treasury management as you juggle debt, equity and investments in a bid to make money through
          financial operations
        </td>
      </tr>
      <tr>
        <td>
          <%= image_tag("balance.png", :size => "64x64") %>
        </td>
        <td>
          Experience the exquisite balance required to manage the need for short term focus in financial decision making with a long term vision for the company
        </td>
      </tr>
    </table>
  </div>

</div>

<!-- /container -->

app/views/welcome/index.html.erb
This is the root page
<br>
<% if user_signed_in? %>
    <% if current_user.facilitator? %>

        <%= link_to "create new student group", new_student_group_path %><br>
        <%= link_to "create new institute student (import)", new_import_path %> <br>
        <%= link_to "create new simulation", new_simulation_path %>


    <% end %>

    <% if current_user.admin? %>
        <!--this is to create a new institute-->
        <%= link_to "create new institute", new_institute_path %><br>
        <%= link_to "create new facilitator", new_facilitator_path %>



    <% end %>

<% end %>

app/views/welcome/landing_page.html.erb
<%= content_for :head do %>
    <script type="text/javascript">
        $(function() {
            //document.getElementByClass("content").style.height='450px';

            $("#carousel").CloudCarousel({
                reflHeight: 56,
                reflGap:2,
                titleBox: $('#title-text'),
                altBox: $('#alt-text'),
                buttonLeft: $('#left-but'),
                buttonRight: $('#right-but'),
                yRadius:60,
                xPos: 385,
                yPos: 120,
                speed:0.15,
                mouseWheel:true
            });
            $('.nature').mobilyblocks({
                trigger: 'hover',
                direction: 'counter',
                duration: 500,
                widthMultiplier: 1.05,

            });
        });
    </script>

    <style>
        .carouselLeft {
            display: none;
            background: url('/assets/arrow-prev.png');
            width: 40px;
            height: 50px;
            background-position: 0px 0px;
            background-repeat: no-repeat;
        }

        .carouselLeft:hover {
            width: 40px;
            height: 40px;
            background-position: 0px -2px;
            cursor: pointer;
        }

        .carouselRight {
            display: none;
            background: url('/assets/arrow-next.png');
            width: 40px;
            height: 50px;
            background-position: 0px 0px;
            background-repeat: no-repeat;

        }

        .carouselRight:hover {
            width: 40px;
            height: 40px;
            background-position: 0px -2px;
            cursor: pointer;
        }

        #title-text {
            display: none;
            color: #f90;
            font-family: Georgia, "Times New Roman", Times, serif;
            font-size: 17px;
            font-weight: bold;
            margin: 20px;
            text-transform: uppercase;
            letter-spacing: 1px;
            margin-bottom: 10px;
            width: 80%;
        }

        #alt-text {
            display: none;
            color: #ddd;
            margin: 20px;
            margin-top: 0px;
            font-size: 14px;
            font-weight: bold;

        }

            /* */

    </style>
    <%= stylesheet_link_tag '/assets/exclusions/mobily' %>

<% end %>

<%= content_for :page_header do %>
    <div style="border: none;margin-top: 15px;"><%= image_tag('logo_white.png') %></div>
<% end %>

<% if current_user %>
    <!--Superadmin View-->
    <% if current_user.superadmin %>
        <div id="carousel" style="border-radius: 10px;width:750px; height:420px;background: url('/assets/carousel.gif');overflow:scroll;">
          <%#= link_to image_tag("mathematical_2.png", :title =>'Mathematical Models', :alt =>'Manage Mathematical Models', :class=>"cloudcarousel"), new_mathematical_model_path %>
          <%= link_to image_tag("market_2.png", :title=>'Markets', :alt=>'Manage Markets', :class=>"cloudcarousel"), view_map_path %>
          <%#= link_to image_tag('decision_manage2.png', :title =>'Decision Parameters', :alt => 'Manage Decision Parameters', :class=>"cloudcarousel"), decision_parameters_path %>
          <%= link_to image_tag('national_2.png', :title =>'National Dealers', :alt =>'Manage National Dealers', :class=>"cloudcarousel"), dealers_path %>
          <%= link_to image_tag('product_2.png', :title =>"Products", :alt =>"Manage Products", :class=>"cloudcarousel"), products_path %>
          <%= link_to image_tag("raw_material_2.png", :title => 'Raw Materials', :alt => 'Manage Raw Materials', :class=>"cloudcarousel"), raw_materials_path %>
          <%= link_to image_tag("market_distance_2.png", :title => "Market Distances", :alt => "Manage Market Distances", :class=>"cloudcarousel"), view_tabular_market_distance_path %>
          <%= link_to image_tag("factory_2.png", :title =>"Factories", :alt =>"Manage Factories", :class=>"cloudcarousel"), factories_path %>
          <%= link_to image_tag("expense_types_2.png", :title =>"Expense Types", :alt =>"Manage Expense Types", :class=>"cloudcarousel"), expense_types_path %>
          <%= link_to image_tag("media_sup_2.png", :title =>"Media", :alt =>"Manage Media", :class=>"cloudcarousel"), media_path %>
          <%= link_to image_tag("media_unit_2.png", :title =>"Media Units", :alt =>"Manage Media Units", :class=>"cloudcarousel"), units_path %>
          <%= link_to image_tag("media_impact_2.png", :title =>"Media Impacts", :alt =>"Manage Media Impacts", :class=>"cloudcarousel"), impacts_path %>
          <%= link_to image_tag("constant_2.png", :title =>"Constants", :alt =>"Manage Constants", :class=>"cloudcarousel"), constants_path %>
          <%= link_to image_tag("investmwent_types_2.png", :title =>"Investment Types", :alt =>"Manage Investment Types", :class=>"cloudcarousel"), investment_types_path %>
          <%= link_to image_tag("loan_types_2.png", :title =>"Loan Types", :alt =>"Manage Loan Types", :class=>"cloudcarousel"), loan_types_path %>
          <div id="title-text"></div>
          <div id="alt-text"></div>
          <div id="left-but" class="carouselLeft" style="position:absolute;top:20px;right:64px;"></div>
          <div id="right-but" class="carouselRight" style="position:absolute;top:20px;right:20px;"></div>
        </div>
        <!--admin view-->
    <% elsif current_user.admin %>
        <div id="carousel" style="border-radius: 10px;width:750px; height:400px;background: url('/assets/carousel.gif');overflow:scroll;">
          <%= link_to image_tag("client2.png", :title =>'Manage Clients', :alt =>'Manage Clients', :class=>"cloudcarousel"), clients_path %>
          <%= link_to image_tag("fac2.png", :title =>'Manage Facilitators', :alt =>'Manage Facilitators', :class=>"cloudcarousel"), facilitators_path %>
          <%#= link_to image_tag("envparameter2.png", :title =>'Manage Environmental Parameters', :alt =>'Manage Environmental Parameters', :class=>"cloudcarousel"), environmental_parameters_path %>
          <%#= link_to image_tag("decision_manage2.png", :title =>'Manage Decision Parameters', :alt =>'Manage Decision Parameters', :class=>"cloudcarousel"), decision_parameters_path %>
          <%= link_to image_tag("media_2.png", :title => 'Manage Media Plans', :alt => 'Manage Media Plans', :class=>"cloudcarousel"), media_plans_path %>
          <%= link_to image_tag("consumer_icon2.png", :title => 'Manage Consumer Categories', :alt => 'Manage Consumer Categories', :class=>"cloudcarousel"), consumer_categories_path %>
          <%= link_to image_tag("employee_2.png", :title =>"Manage Employee Category", :alt =>"Manage Employee Category", :class=>"cloudcarousel"), employee_categories_path %>
          <%= link_to image_tag("expenses_2.png", :title =>"Manage Expenses", :class=>"cloudcarousel"), expenses_path %>
          <%= link_to image_tag("investmwent_2.png", :title =>"Manage Investments", :alt =>"Manage Investments", :class=>"cloudcarousel"), investments_path %>
          <%= link_to image_tag("loan_2.png", :title =>"Manage Loans", :alt =>"Manage Loans", :class=>"cloudcarousel"), loans_path %>
          <%= link_to image_tag("mass_upload_2.png", :title =>"Mass Upload Users", :alt =>"Mass Upload Users", :class=>"cloudcarousel"), imports_path %>
          <%= link_to image_tag("default_player_2.png", :title =>"Default Player Data", :alt =>"Default Player Data", :class=>"cloudcarousel"), new_default_player_datum_path %>
          <div id="title-text"></div>
          <div id="alt-text"></div>
          <div id="left-but" class="carouselLeft" style="position:absolute;top:20px;right:64px;"></div>
          <div id="right-but" class="carouselRight" style="position:absolute;top:20px;right:20px;"></div>
        </div>

        <!--facilitator view-->
    <% elsif current_user.facilitator %>

        <div align="center">
          <%= link_to image_tag("factory_2.png",:size=>"200x250", :title => 'Manage Facilitator Group', :alt => 'Manage Facilitator Group', :class=>"cloudcarousel"), participation_management_path %>
          <%#= link_to image_tag("case_study_2.png", :title => 'Manage My CaseStudies', :alt => 'Manage My CaseStudies', :class=>"cloudcarousel"), case_studies_path %>
                                                         &nbsp;
                                                         &nbsp;
                                                         &nbsp;
                                                         &nbsp;
                                                         &nbsp;
          <%= link_to image_tag("cfo.png",:size=>"200x250", :title => 'My CaseStudies', :alt => 'Manage My CaseStudies', :class=>"cloudcarousel"), simulations_path %>
          </div>


        <!--player view-->
    <% elsif current_user.student %>
        <script type='text/javascript'>
          $(function(){
          $('.content').css('height','450px');
          });
        </script>
        <p style="font-size:24px;">There are simulations assigned to you...</p>
        <div class="mobily" style="margin-left:620px; ">
          <div class="nature">
            <ul class="reset">
              <li><a href=<%= edit_brand_path(@brand) %>><img id="decision_forms" src="/assets/decision_icon.png" alt=""/></a>
              </li>
              <li><a href="#"><img id="market_data" src="/assets/market_data_icon.png" alt=""/></a></li>
              <li><a href="#"><img id="round_results" src="/assets/round_result_icon.png" alt=""/></a></li>
              <li><a href="#"><img id="leaderboard" src="/assets/leaderboard.png" alt=""/></a></li>
            </ul>
          </div>
        </div>
        <ul style="font-size:24px;">
          <% @simulations.each_with_index do |simulation, index| %>
              <% if simulation.initiated? %>
                  <% @active_round=ActiveRound.find_by_simulation_id(simulation.id).round_id %>
                  <li style="font-size: 24px;"><%= simulation.name %> <%= link_to "View Brands", brands_path(:player_id=> @players[index].id, :round_id=>@active_round) %>
              <% end %>

          <% end %>
        </ul>

    <% end %>
<% end %>

app/views/welcome/old_index.html.erb
<%= content_for :page_header do %>

    <h1> Home Page </h1>

<% end %>
<%= content_for :secondary_area do %>
<%= link_to "Go To Startup Decision Page >> ",new_start_up_decision_path,:class=>"primary btn" %>
<%= link_to "Go To Reports(PnL) >> ",new_start_up_decision_path,:class=>"primary btn" %>

    <% end %>



    <p> A biscuit (play /ˈbɪskɨt/) is a baked, edible, and commonly flour-based product. The term is used to apply to
      two distinctly different products in North America and the Commonwealth Nations.

      In the United States it is a small, soft, leavened bread, somewhat similar to a scone. A Southern regional
      variation on the term, beaten biscuit, is closer to the British form.
      In Commonwealth English, it is a small and hard, often sweet, baked product that would be called either a cookie
      or a cracker in the United States, and either a biscuit or a cookie in Canada. Biscuits in the British Isles may
      be savoury (savoury biscuits are often referred to as "crackers") or sweet, such as chocolate biscuits, ginger
      nuts, custard creams or the Nice biscuit.
    </p>

    <p>
      The modern-day confusion in the English language around the word "biscuit" is created by its etymology.

      The Middle French word bescuit is derived from the Latin words bis (twice) and coquere, coctus (to cook, cooked),
      and, hence, means "twice-cooked".[1] This is because biscuits were originally cooked in a twofold process: first
      baked, and then dried out in a slow oven.[2]

      This term was then adapted into English in the 14th century during the Middle Ages, in the Middle English word
      bisquite, to represent a hard, twice-baked product.[3]

      However, the Dutch language from around 1703 had adopted the word koekje, a language diminutive of cake, to have a
      similar meaning for a similar hard, baked product.[4] This may be related[citation needed] to the Russian or
      Ukrainian translation, where "biscuit" has come to mean "sponge cake".

      The difference between the secondary Dutch word and that of Latin origin is that, whereas the koekje is a cake
      that rises during baking, the biscuit, which has no raising agent, in general does not (see gingerbread/ginger
      biscuit), except for the expansion of heated air during baking.[citation needed]

      When peoples from Europe began to emigrate to the United States, the two words and their "same but different"
      meanings began to clash. After the American War of Independence against the British, the word cookie became the
      word of choice to mean a hard, twice-baked product.[citation needed]

      Further confusion has been added by the adoption of the word biscuit for a small leavened bread popular in the
      United States.

      Today, according to American English dictionary Merriam-Webster:

      A cookie is a "small flat or slightly raised cake".[4]
      A biscuit is "any of various hard or crisp dry baked product" similar to the American English terms cracker or
      cookie.[3]
      A biscuit can also mean "a small quick bread made from dough that has been rolled out and cut or dropped from a
      spoon".[3]

      Today, throughout most of the world, the term biscuit still means a hard, crisp, brittle bread, except in the
      United States, where it now denotes a softer bread product baked only once. In modern Italian usage, the term
      biscotto is used to refer to any type of hard twice-baked biscuit, and not only to the cantuccini as in the past.
    </p>

app/views/welcome/participation_management.html.erb
<style type="text/css">
    .btn {
        height: 30px;
        font-size: 16px

    }

    .add_remove_button {
        width: 20px;
        height: 20px
    }

    .list_of_students {

        /*border: 1px solid black;*/
        padding: 10px;
        border-radius: 10px;
    }

    .student_name {
        /*background: white;*/
        border: 1px solid #000000;
        /*border-radius: 12px;*/
        padding: 10px;

    }

    .remove_icon {
        float: right;

    }

    .students {
        height: 310px;
        overflow: auto;
    }

    .student_group_info {

        /*border: 1px solid black;*/
        /*padding: 10px;*/
        height: 250px;
        overflow: auto;
        border: none;

    }

    .include {

        margin-top: 200px;
    }

    .exclude {
        margin-top: 300px;
    }


</style>


<script type="text/javascript">


    function get_available_students(student_group_id) {
        //get list of all students who can still  be added
        $.get("student_group_users/new?student_group_id=" + student_group_id, function(data) {
            $(".students ").html(data);

        });


    }

    function get_included_students(student_group_id) {
        $.get("/student_group_users?student_group_id=" + student_group_id, function(data) {
            $(".student_group_info").html(data);

        });


    }


    $(function() {


        $("a").css("text-align", "center");

        $(".page-header").css("height", "50px");

        $(".modal").modal({
            backdrop: true,
            keyboard: true
        });
      //  $(".modal").modal().hide();


        $(".new_group").click(function(event) {

            $("#new_student_group").modal('toggle');
            event.preventDefault();


        });

//        $(".new_simulation").click(function(event) {
//
//            $("#simulation_assignment").modal('toggle');
//            event.preventDefault();
//
//
//        });

//         $(".new_upload").click(function(event) {
//
//            $("#new_import").modal('show');
//            event.preventDefault();
//
//
//        });

        $("simulation_form").click(function() {

            $(".student_group_simulation").attr("value", ($(".list option:selected").attr("value")));
        });


        get_available_students("<%=@selected_student_group.id %>");

        get_included_students("<%=@selected_student_group.id %>");


        //get list of all students who are in the particular group


        $(".list").change(function() {
            //    $(".hidden_student_group").attr("value", $("select option:selected").attr("value"));
            get_available_students($(".list option:selected").attr("value"));

            get_included_students($(".list option:selected").attr("value"));


        });


        $(".remove_icon").live("click", function() {

            $.get("remove_student/" + $(this).attr("id"), function() {

                get_available_students($(".list option:selected").attr("value"));
                get_included_students($(".list option:selected").attr("value"));


            });


        });


        $(".remove_icon_main").live("click", function() {

            $.get("remove_student_from_list/" + $(this).attr("id"), function() {

                get_available_students($(".list option:selected").attr("value"));


            });
        });


    });

</script>


<!--modal for creating a new student group-->
<div class="modal hide fade" id="new_student_group">

  <div class="modal-header">
    <a href="#" class="close">×</a>

    <h3>Create A New Student Group</h3>
  </div>
  <div class="modal-body">
    <%= render 'student_groups/form' %>
  </div>


</div>

<!--modal for assigning simulation-->
<!--<div class="modal hide fade" id="simulation_assignment">-->

<!--<div class="modal-header">-->
<!--<a href="#" class="close">×</a>-->

<!--<h3>Assign Simulation</h3>-->
<!--</div>-->

<!--<div class="modal-body">-->
<!--<%#= form_tag :action => 'set_simulation' %>-->

<!--<%#= select_tag "simulation_id", options_from_collection_for_select(Simulation.all, "id", "name") %>-->

<!--<%#= hidden_field_tag :student_group_id, @selected_student_group.id, :class=>"student_group_simulation" %>-->
<!--<br><br>-->
<!--<%#= submit_tag "OK", :class=>"simulation_form primary btn" %>-->

<!--</div>-->


<!--</div>-->

<!--modal for upload -->
<div class="modal hide fade" id="new_import">

  <div class="modal-header">
    <a href="#" class="close">×</a>

    <h3>New Import</h3>
  </div>
  <div class="modal-body">
    <%= render :file=> 'imports/new' %>

  </div>


</div>



<!--main page-->
<div class="row" style="margin-left: 15px;">

  <!--This is where list of all students should come-->

  <div class="span5 list_of_students ">
    <div class="label " style="background: #0000CD;font-size: 16px;height: 45px;text-align: center;"><br/>List Of All
      Students
    </div>



    <%= form_tag :action => 'set_participation' %>
    <div class="students">

    </div>


  </div>

  <div class="span1">
    <div class="add_remove_button">
      <%= submit_tag(">>", :class=>"include btn") %>
    </div>


  </div>


  <div class="span8" style="margin-top: 10px;margin-left: 40px">

    <div class="row">
      <%#= link_to "UPLOAD STUDENTS", new_import_path(:facilitator_group_id=>@facilitator_group.id), :class=>"new_upload primary btn span8" %>
      <%= link_to image_tag("upload.png", :size=>"350x50"), new_import_path(:facilitator_group_id=>@facilitator_group.id), :class=>"new_upload  span8", :style => "margin-left:-35px" %>
    </div>


    <br>


    <div class="row">
      <div class="span4" style="margin-left: 25px;">
        <div class="row">
          <%= @student_group.id %>
          <div class="input" style="">
            <%= select_tag "student_groups", options_from_collection_for_select(@student_groups, "id", "name", @selected_student_group.id), :class=>"list span4" %>
          </div>
        </div>

        <br>


        <div class="row">
          <div class="student_group_info">


          </div>
        </div>
      </div>
      <div class="span3" style="margin-top: 50px;margin-left: 50px;">
        <div class="row">
          <%#= link_to "ADD GROUP", "", :class=>"new_group primary btn span3" %>
          <%= link_to image_tag("add_group.png", :size=>"100x100"), "", :class=>"new_group span3 offset1" %>
        </div>


        <br>

        <div class="row">
          <%#= link_to "ASSIGN SIMULATION", "", :class=>"new_simulation primary btn span3", :style => 'height:auto;' %>
          <%= link_to image_tag("assign_simulation.png"), "", :class=>"new_simulation  span3 offset1", :style => 'height:auto;' %>
        </div>
      </div>

      <br>
      <br>


    </div>
  </div>


</div>